name: golang-pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0' # Specify your Go version
      - name: Install Dependencies
        run: go mod download
      - name: Build the Go Application
        run: go build -v ./...
      - name: Run Tests
        run: go test -v ./...
